# Manejando Datos Extraviados

En este JNB se revisará el tema de manejo de datos extraviados.

In [ ]:
import pandas as pd
import numpy as np
from pathlib import Path

np.random.seed(0)

BASE_DIR = Path.cwd()
DATA_DIR = BASE_DIR / "data"

print("Directorio de trabajo:", BASE_DIR)
print("Carpeta de datos:", DATA_DIR)

nfl_path = DATA_DIR / "NFL.csv"

if nfl_path.exists():
    nfl_data = pd.read_csv(nfl_path, low_memory=False)
    print("\nDataset NFL cargado correctamente.")
    print("Dimensiones:", nfl_data.shape)

    # Mostrar las primeras cinco filas
    display(nfl_data.head())

    missing_values_count = nfl_data.isnull().sum()

    print("\nValores faltantes en las primeras 10 columnas:")
    display(missing_values_count.iloc[:10])

    total_cells = np.prod(nfl_data.shape)
    total_missing = missing_values_count.sum()
    percent_missing = (
        total_missing / total_cells * 100 if total_cells else 0
    )

    print(f"\nTotal de celdas: {total_cells:,}")
    print(f"Total de valores faltantes: {total_missing:,}")
    print(f"Porcentaje de valores faltantes: {percent_missing:.2f}%")

    print("\nColumnas con más valores faltantes:")
    display(
        missing_values_count[missing_values_count > 0]
        .sort_values(ascending=False)
        .head(15)
    )

    nfl_data_dropped_rows = nfl_data.dropna()

    print("\nDespués de eliminar filas con valores faltantes:")
    print("Filas originales:", len(nfl_data))
    print("Filas restantes:", len(nfl_data_dropped_rows))


    columns_with_na_dropped = nfl_data.dropna(axis=1)

    print("\nDespués de eliminar columnas con valores faltantes:")
    print("Columnas originales:", nfl_data.shape[1])
    print("Columnas restantes:", columns_with_na_dropped.shape[1])

    display(columns_with_na_dropped.head())

    # En el tutorial original se seleccionan las columnas
    # EPA hasta Season. Si existen, se utiliza ese rango.
    if "EPA" in nfl_data.columns and "Season" in nfl_data.columns:
        subset_nfl_data = nfl_data.loc[:, "EPA":"Season"].head().copy()
    else:
        # Alternativa para un CSV NFL con columnas diferentes
        subset_nfl_data = nfl_data.head().copy()

    print("\nSubconjunto original:")
    display(subset_nfl_data)

    print("\nValores faltantes reemplazados por cero:")
    display(subset_nfl_data.fillna(0))

    # bfill funciona en versiones actuales de pandas.
    # Los valores faltantes que sigan al final se rellenan con 0.
    subset_filled = subset_nfl_data.bfill(axis=0).fillna(0)

    print("\nValores rellenados con el siguiente valor y luego cero:")
    display(subset_filled)

else:
    print("\nNo se encontró data/NFL.csv.")
    print("Archivos CSV disponibles:")
    if DATA_DIR.exists():
        for file in DATA_DIR.glob("*.csv"):
            print(" -", file.name)
    else:
        print("No existe la carpeta data/.")

Directorio de trabajo: /workspaces/GTD2401-ACD-GA-EJ26-04-pandas-clean-brgael
Carpeta de datos: /workspaces/GTD2401-ACD-GA-EJ26-04-pandas-clean-brgael/data

Dataset NFL cargado correctamente.
Dimensiones: (2, 1)

          version https://git-lfs.github.com/spec/v1
0  oid sha256:2433f41d45abe53ba842b5ddc529d574d04...
1                                     size 275530460

Valores faltantes en las primeras 10 columnas:

version https://git-lfs.github.com/spec/v1    0
dtype: int64

Total de celdas: 2
Total de valores faltantes: 0
Porcentaje de valores faltantes: 0.00%

Columnas con más valores faltantes:

Series([], dtype: int64)

Después de eliminar filas con valores faltantes:
Filas originales: 2
Filas restantes: 2

Después de eliminar columnas con valores faltantes:
Columnas originales: 1
Columnas restantes: 1

          version https://git-lfs.github.com/spec/v1
0  oid sha256:2433f41d45abe53ba842b5ddc529d574d04...
1                                     size 275530460

Subconjunto original:

          version https://git-lfs.github.com/spec/v1
0  oid sha256:2433f41d45abe53ba842b5ddc529d574d04...
1                                     size 275530460

Valores faltantes reemplazados por cero:

          version https://git-lfs.github.com/spec/v1
0  oid sha256:2433f41d45abe53ba842b5ddc529d574d04...
1                                     size 275530460

Valores rellenados con el siguiente valor y luego cero:

          version https://git-lfs.github.com/spec/v1
0  oid sha256:2433f41d45abe53ba842b5ddc529d574d04...
1                                     size 275530460